server:
  port: 
spring:
  application:
    name: service-user
  servlet:
    multipart:
      max-file-size: 100MB #单个文件上传大小,默认1M
      max-request-size: 100MB #总文件上传大小，默认10M
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///studyweb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username:
      password: 
  cloud:
    nacos:
      server-addr: 
  mail:
    host: smtp.qq.com
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          #如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true
  #redis配置
  redis:
    host: 
    #host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 32
        #最大阻塞等待时间
        max-wait: 300ms
        #最大空闲连接
        max-idle: 16
        min-idle: 8

  cache:
    redis:
      time-to-live: 1800000
    type: redis

#mybatis配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#存储位置
studyweb:
  endpoint: 
  secretid:
  secretkey: 
  bucketname: rabbit-studyweb


#阿里云支付配置
alipay:
  appId: 2016102600763473
  appPrivateKey:
  alipayPublicKey:
  notifyUrl: http://ip:端口号/aliPay/notify
  returnUrl: http://ip:端口号/front/order

zhenzikj:
  url:
  appId: 
  appSecret: 
  templateId: 
ribbon:
  eager-load:
    enabled: true
    clients: servicevod #指定饥饿加载的服务名称
feign:
  httpclient:
    enabled: true #开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
